## LIBRERIAS

In [1]:
import numpy as np

## CONTRACCIÓN A LO LARGO DEL EJE i

En primer lugar, vamos a calcular la contracción a lo largo del eje i. Si consideramos la multiplicación de un tensor T 3D y una matrix W 2D, entonces es equivalente a segmentar el eje i del tensor en las matrices que lo componen y realizar la multiplicación de la matrix W por cada una de las submatrices que surgen del tensor. En primer lugar, vemos el primer caso que sería cuando el número de matrices en la dimensión i es solo uno y por lo tanto es la multiplicación usual

In [65]:
### MULTIPLICACIÓN POR LA IZQUIERDA -> 2 Dimensiones

np.random.seed(0)
arr1 = np.random.randint(-5, 5, (2, 2))
arr2 = np.random.randint(-5, 5, (2, 2))

print(arr1)

result = np.einsum('lj,jk->lk', arr2, arr1)


print(result)

print(np.dot(arr2,arr1))

[[ 0 -5]
 [-2 -2]]
[[ -8 -18]
 [  0  10]]
[[ -8 -18]
 [  0  10]]


Cuando no se trata de multiplicación de tensores en 2D, sino que uno de ellos es un tensor 3D, entonces el tensor resultante avanza en el eje i realizando multiplicaciones iguales a las que se tenian en el caso de la multiplicación de matrices

In [83]:
### MULTIPLICACIÓN POR LA IZQUIERDA

np.random.seed(0)
arr1 = np.random.randint(-5, 5, (2, 2, 2))
arr2 = np.random.randint(-5, 5, (2, 2))

print(arr1)

result = np.einsum('lj,ijk->ilk', arr2, arr1)


print(result)

print(np.dot(arr2,arr1[0,:,:])+np.dot(arr2,arr1[1,:,:]))

[[[ 0 -5]
  [-2 -2]]

 [[ 2  4]
  [-2  0]]]
[[[  2  17]
  [ -2 -12]]

 [[ -4 -12]
  [  2   8]]]
[[-2  5]
 [ 0 -4]]


In [92]:
### MULTIPLICACIÓN POR LA DERECHA

np.random.seed(10)
arr1 = np.random.randint(-3, 3, (2, 2, 2))
arr2 = np.random.randint(-3, 3, (2, 2))

print(arr1)

result = np.einsum('ijk,kl->ijl', arr1, arr2)

print(result)

print(np.array([np.dot(arr1[0,:,:],arr2),np.dot(arr1[1,:,:],arr2)]))

[[[-2  2]
  [ 1 -3]]

 [[-2  0]
  [ 1 -2]]]
[[[ 0  2]
  [-4  3]]

 [[-4  6]
  [-2  1]]]
[[[ 0  2]
  [-4  3]]

 [[-4  6]
  [-2  1]]]


## CONTRACCION EN EL EJE J

In [85]:
#### MULTIPLICACIÓN POR LA IZQUIERDA

np.random.seed(0)
arr1 = np.random.randint(-3, 3, (2, 2, 2))
arr2 = np.random.randint(-3, 3, (2, 2))

print(arr1)
## Cortes ej j

print(' -------  Cortes ej j  ------- \n')
print(arr1[:,0,:])
print(arr1[:,1,:])

## Cuando hago cortes las matrices que me quedan son del tipo ixk -> Por lo tanto contraigo el eje i de la matrix (tomando la matriz como lxi) con el eje i del tensor
print('------- Resultado  ------- \n')

result = np.einsum('li,ijk->jkl', arr2, arr1)

print(result)

print(np.dot(arr2,arr1[:,0,:])+np.dot(arr2,arr1[:,1,:]))

[[[ 1  2]
  [-3  0]]

 [[ 0  0]
  [-2  0]]]
 -------  Cortes ej j  ------- 

[[1 2]
 [0 0]]
[[-3  0]
 [-2  0]]
------- Resultado  ------- 

[[[ 2  1]
  [ 4  2]]

 [[-4  3]
  [ 0  0]]]
[[-2  4]
 [ 4  2]]


In [86]:
#### MULTIPLICACIÓN POR LA DERECHA

np.random.seed(0)
arr1 = np.random.randint(-3, 3, (2, 2, 2))
arr2 = np.random.randint(-3, 3, (2, 2))

print(arr1)

## Cortes ej j

print(' -------  Cortes ej j  ------- \n')
print(arr1[:,0,:])
print(arr1[:,1,:])

## Cuando hago cortes las matrices que me quedan son del tipo ixk -> Por lo tanto contraigo el eje k con el eje k de la matriz 2
result = np.einsum('ijk,kl->jil', arr1, arr2)

print('------- Resultado  ------- \n')
print(result)

print(np.dot(arr1[:,0,:],arr2)+np.dot(arr1[:,1,:],arr2))

[[[ 1  2]
  [-3  0]]

 [[ 0  0]
  [-2  0]]]
 -------  Cortes ej j  ------- 

[[1 2]
 [0 0]]
[[-3  0]
 [-2  0]]
------- Resultado  ------- 

[[[ 4 -7]
  [ 0  0]]

 [[-6  3]
  [-4  2]]]
[[-2 -4]
 [-4  2]]


## CONTRACCION EN EL EJE K

In [95]:
#### MULTIPLICACIÓN POR LA IZQUIERDA

np.random.seed(0)
arr1 = np.random.randint(-3, 3, (2, 2, 2))
arr2 = np.random.randint(-3, 3, (2, 2))

print(arr1)
## Cortes ej j

print(' -------  Cortes ej k  ------- \n')
print(arr1[:,:,0])
print(arr1[:,:,1])

## Cuando hago cortes las matrices que me quedan son del tipo ixj -> Por lo tanto contraigo el eje i de la matrix (tomando la matriz como lxi) con el eje i del tensor
print('------- Resultado  ------- \n')

result = np.einsum('li,ijk->klj', arr2, arr1)

print(result)

print(np.array([np.dot(arr2,arr1[:,:,0]),np.dot(arr2,arr1[:,:,1])]))

[[[ 1  2]
  [-3  0]]

 [[ 0  0]
  [-2  0]]]
 -------  Cortes ej j  ------- 

[[ 1 -3]
 [ 0 -2]]
[[2 0]
 [0 0]]
------- Resultado  ------- 

[[[ 2 -4]
  [ 1  3]]

 [[ 4  0]
  [ 2  0]]]
[[[ 2 -4]
  [ 1  3]]

 [[ 4  0]
  [ 2  0]]]


In [98]:
np.random.seed(0)
arr1 = np.random.randint(-3, 3, (2, 2, 2))
arr2 = np.random.randint(-3, 3, (2, 2))

print(arr1)
## Cortes ej j

print(' -------  Cortes ej j  ------- \n')
print(arr1[:,:,0])
print(arr1[:,:,1])

print('------- Resultado  ------- \n')

# Cuando hago cortes las matrices que me quedan son del tipo ixj -> Por lo tanto contraigo el eje j del tensor con el eje j de la matriz 2
result = np.einsum('ijk,jl->kil', arr1, arr2)

print(result)

print(np.array([np.dot(arr1[:,:,0],arr2),np.dot(arr1[:,:,1],arr2)]))
print(np.dot(arr1[:,:,0],arr2)+np.dot(arr1[:,:,1],arr2))

[[[ 1  2]
  [-3  0]]

 [[ 0  0]
  [-2  0]]]
 -------  Cortes ej j  ------- 

[[ 1 -3]
 [ 0 -2]]
[[2 0]
 [0 0]]
------- Resultado  ------- 

[[[-1  8]
  [-2  6]]

 [[ 4 -2]
  [ 0  0]]]
[[[-1  8]
  [-2  6]]

 [[ 4 -2]
  [ 0  0]]]
[[ 3  6]
 [-2  6]]
